image: docker:latest

variables:
  FTP_SHOST: ftp.bluewindlab.com
  FTP_SUSERNAME: u168445203.projects_staging
  FTP_HOST: ftp.bluewindlab.net
  FTP_PUSERNAME: u138608855.projects_production
  BUILD_DIR: /builds/wpfm-addon/wpfm-faq-collector-addon
  DEPLOY_DIR: wpfm/wp-content/plugins/wpfm-faq-collector-addon
stages:
  - staging
  - production

before_script:
  - apk add lftp

staging:
  stage: staging
  only:
    - staging
  tags:
    - ci
    - devops
  script:
    - pwd
    - lftp -e "set ssl:verify-certificate no; open $FTP_SHOST; user $FTP_SUSERNAME $FTP_SPASSWORD; mirror -X .* -X .*/ --reverse --verbose $BUILD_DIR /wpplugins/$DEPLOY_DIR; bye"

production:
  stage: production
  only:
    - production
  tags:
    - ci
    - devops
  script:
    - pwd
    - lftp -e "set ssl:verify-certificate no; open $FTP_HOST; user $FTP_PUSERNAME $FTP_PPASSWORD; mirror -X .* -X .*/ --reverse --verbose $BUILD_DIR /wpplugin/$DEPLOY_DIR; bye"
